version:  '3.5'

services:
  db:
    container_name: ecolejp_db
    image: mysql:5.7
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_password

  phpmyadmin:
    container_name : academix_myadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - "9702:80"
    depends_on:
      - db
    environment:
      PMA_HOST: db

  nginx:
    container_name : academix_nginx
    image: nginx:1.15.3-alpine
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 2525:80
    depends_on:
      - php

  php:
    container_name : ecolejp_php
    build:
      context: ./docker/php
    volumes:
      - .:/var/www

###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
  dbdata:

###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
